#!/bin/sh
# Copyright (c) 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: afpd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown
# XQUERY: -i "count(//afp/enable) > 0" -o "0" -b
# RCVAR: afpd

. /etc/rc.subr
. /etc/configxml.subr

name="afpd"
rcvar=`set_rcvar`

# Custom commands
start_precmd="create_conf"

# Defaults
afpd_enable=${afpd_enable:-"NO"}
afpd_config=${afpd_config:-"/var/etc/${name}.conf"}
afpd_avdefault=${afpd_avdefault:-"/var/etc/AppleVolumes.default"}
afpd_avsystem=${afpd_avsystem:-"/var/etc/AppleVolumes.system"}
command="/usr/local/sbin/${name}"
command_args="-F ${afpd_config}"

create_conf()
{
	# Create config file.
	/usr/local/bin/xml sel -t -m "//afp" \
		-i "string-length(afpname) > 0" -v "concat('&quot;',afpname,'&quot;')" -b \
		-i "string-length(afpname) = 0" -o "-" -b \
		-o " -noddp -uamlist " \
		-i "count(guest) > 0" -o "uams_guest.so" -b \
		-i "count(local) > 0" -i "count(guest) > 0" -o "," -b -o "uams_clrtxt.so,uams_randnum.so,uams_dhx_passwd.so,uams_dhx.so" -b \
		-o " -nosavepassword -defaultvol /var/etc/AppleVolumes.default -systemvol /var/etc/AppleVolumes.system -uservol -uampath /etc/uams -guestname &quot;ftp&quot;" -n \
		${configxml_file} | /usr/local/bin/xml unesc > ${afpd_config}

	# Generate '/var/etc/AppleVolumes.system'.
	/usr/local/bin/xml sel -t -m "//mounts/mount" \
		-v "concat('&quot;/mnt/',sharename,'&quot; &quot;',sharename,'&quot; ')" \
		-o "options:usedots allow:@admin" \
		-n \
		${configxml_file} | /usr/local/bin/xml unesc > ${afpd_avsystem}

	# Generate /var/etc/AppleVolumes.default
	/usr/local/bin/xml sel -t -m "//afp/share" \
		-v "concat('&quot;',path,'&quot; &quot;',name,'&quot; ')" \
		-i "string-length(volpasswd) > 0" -v "concat('password:', volpasswd, ' ')" -b \
		-i "not(casefold[. = 'none'])" -v "concat('casefold:', casefold, ' ')" -b \
		-i "string-length(volcharset) > 0" -v "concat('volcharset:', volcharset, ' ')" -b \
		-o "options:usedots" \
		-i "count(mswindows) > 0" -o ",mswindows" -b \
		-i "count(noadouble) > 0" -o ",noadouble" -b \
		-o " " \
		-i "string-length(allow) > 0" -v "concat('allow:', allow, ' ')" -b \
		-i "string-length(deny) > 0" -v "concat('deny:', deny, ' ')" -b \
		-i "string-length(rolist) > 0" -v "concat('rolist:', rolist, ' ')" -b \
		-i "string-length(rwlist) > 0" -v "concat('rwlist:', rwlist, ' ')" -b \
		-n \
		${configxml_file} | /usr/local/bin/xml unesc > ${afpd_avdefault}
}

load_rc_config ${name}
run_rc_command "$1"
