#!/bin/sh
# Copyright (c) 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: afpd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown
# XQUERY: -i "count(//afp/enable) > 0" -o "0" -b
# RCVAR: afpd

. /etc/rc.subr
. /etc/configxml.subr

name="afpd"
rcvar=`set_rcvar`

# Custom commands
start_precmd="create_conf"

# Defaults
afpd_enable=${afpd_enable:-"NO"}
afpd_config=${afpd_config:-"/var/etc/${name}.conf"}
afpd_defaultvol=${afpd_defaultvol:-"/var/etc/AppleVolumes.default"}
command="/usr/local/sbin/${name}"
command_args="-F ${afpd_config}"

create_conf()
{
	# Create config file.
	/usr/local/bin/xml sel -t -m "//afp" \
		-i "string-length(afpname) > 0" -v "concat('&quot;',afpname,'&quot;')" -b \
		-i "string-length(afpname) = 0" -o "-" -b \
		-o " -transall -uamlist " \
		-i "count(guest) > 0" -o "uams_guest.so" -b \
		-i "count(local) > 0" -i "count(guest) > 0" -o "," -b -o "uams_clrtxt.so,uams_dhx.so" -b \
		-o " -noddp -nosavepassword -defaultvol ${afpd_volumes_config} -systemvol /var/etc/AppleVolumes.default -uampath /etc/uams -guestname &quot;ftp&quot;" -n \
		${configxml_file} | /usr/local/bin/xml unesc > ${afpd_config}

	# Generate '/var/etc/AppleVolumes.default'.
	/usr/local/bin/xml sel -t -m "//mounts/mount" \
		-v "concat('/mnt/',sharename,' &quot;',sharename,'&quot;')" -n \
		${configxml_file} | /usr/local/bin/xml unesc > ${afpd_defaultvol}
}

load_rc_config ${name}
run_rc_command "$1"
