#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: beep
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr
. /etc/configxml.subr

name="beep"
start_cmd="start_cmd"
stop_cmd="stop_cmd"

start_cmd()
{
	_disable=$(configxml_isset //system/disablebeep)
	if [ ! _disable ]; then
		echo O3L30cO4L30cO5L30cO5L30g > /dev/speaker
	fi
}

stop_cmd()
{
	_disable=$(configxml_isset //system/disablebeep)
	if [ ! _disable ]; then
		echo O5L30gO5L30cO4L30cO3L30c > /dev/speaker
	fi
}

run_rc_command "$1"
