#!/bin/sh
# Copyright (c) 2007-2009 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: beep
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr
. /etc/configxml.subr

name="beep"
start_cmd="start_cmd"
stop_cmd="stop_cmd"

start_cmd()
{
	if ! configxml_isset //system/disablebeep; then
		if [ -e /dev/speaker ]; then
			echo O3L30cO4L30cO5L30cO5L30g > /dev/speaker
		fi
	fi
}

stop_cmd()
{
	if ! configxml_isset //system/disablebeep; then
		if [ -e /dev/speaker ]; then
			echo O5L30gO5L30cO4L30cO3L30c > /dev/speaker
		fi
	fi
}

run_rc_command "$1"
