#!/bin/sh
# Copyright (c) 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: CONFIG
# REQUIRE: execcmd_preinit rcconf system_init
# BEFORE: NETWORKING NETWORK

#	This is a dummy dependency.
