#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/cron,v 1.7.14.1 2008/01/28 07:58:31 dougb Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
#

# PROVIDE: cron
# REQUIRE: LOGIN cleanvar
# BEFORE: securelevel
# KEYWORD: shutdown

. /etc/rc.subr
. /etc/configxml.subr

name="cron"
rcvar="`set_rcvar`"
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
cron_config=${cron_config:-"/etc/crontab"}

# Custom commands
start_precmd="mkconf_cmd"
mkconf_cmd="mkconf_cmd"
extra_commands="mkconf"

mkconf_cmd()
{
	# Create /etc/crontab
	echo "SHELL=/bin/sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin
HOME=/var/log
#
#minute	hour	mday	month	wday	who	command
#" > ${cron_config}

	# RSYNC client
	if [ 0 -lt `configxml_get_count "//rsync/rsyncclient[enable]"` ]; then
		echo "# Perform RSYNC client." >> ${cron_config}
		/usr/local/bin/xml sel -t -m "//rsync/rsyncclient[enable]" \
			-i "all_mins[. = "0"]" -m minute -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_mins[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_hours[. = "0"]" -m hour -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_hours[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_days[. = "0"]" -m day -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_days[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_months[. = "0"]" -m month -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_months[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_weekdays[. = "0"]" -m weekday -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_weekdays[. != "0"]" -o "*" -b \
			-o " " \
			-v "concat('root /var/run/rsync_client_',uuid,'.sh')" \
			${configxml_file} | /usr/local/bin/xml unesc >> ${cron_config}
	fi

	# RSYNC local
	if [ 0 -lt `configxml_get_count "//rsync/rsynclocal[enable]"` ]; then
		echo "# Perform RSYNC local." >> ${cron_config}
		/usr/local/bin/xml sel -t -m "//rsync/rsynclocal[enable]" \
			-i "all_mins[. = "0"]" -m minute -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_mins[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_hours[. = "0"]" -m hour -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_hours[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_days[. = "0"]" -m day -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_days[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_months[. = "0"]" -m month -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_months[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_weekdays[. = "0"]" -m weekday -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_weekdays[. != "0"]" -o "*" -b \
			-o " " \
			-v "concat('root /var/run/rsync_local_',uuid,'.sh')" \
			${configxml_file} | /usr/local/bin/xml unesc >> ${cron_config}
	fi

	# Scheduled shutdown
	if [ 0 -lt `configxml_get_count "//shutdown/enable"` ]; then
		echo "# Perform scheduled shutdown." >> ${cron_config}
		/usr/local/bin/xml sel -t -m "//shutdown" \
			-i "all_mins[. = "0"]" -m minute -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_mins[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_hours[. = "0"]" -m hour -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_hours[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_days[. = "0"]" -m day -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_days[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_months[. = "0"]" -m month -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_months[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_weekdays[. = "0"]" -m weekday -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_weekdays[. != "0"]" -o "*" -b \
			-o " " \
			-o "root /sbin/shutdown -p now" \
			${configxml_file} | /usr/local/bin/xml unesc >> ${cron_config}
	fi

	# Scheduled reboot
	if [ 0 -lt `configxml_get_count "//reboot/enable"` ]; then
		echo "# Perform scheduled reboot." >> ${cron_config}
		/usr/local/bin/xml sel -t -m "//reboot" \
			-i "all_mins[. = "0"]" -m minute -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_mins[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_hours[. = "0"]" -m hour -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_hours[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_days[. = "0"]" -m day -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_days[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_months[. = "0"]" -m month -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_months[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_weekdays[. = "0"]" -m weekday -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_weekdays[. != "0"]" -o "*" -b \
			-o " " \
			-o "root /sbin/shutdown -r now" \
			${configxml_file} | /usr/local/bin/xml unesc >> ${cron_config}
	fi

	# Email status notification
	if [ 0 -lt `configxml_get_count "//statusreport/enable"` ]; then
		echo "# Perform email status report." >> ${cron_config}
		/usr/local/bin/xml sel -t -m "//statusreport" \
			-i "all_mins[. = "0"]" -m minute -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_mins[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_hours[. = "0"]" -m hour -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_hours[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_days[. = "0"]" -m day -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_days[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_months[. = "0"]" -m month -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_months[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_weekdays[. = "0"]" -m weekday -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_weekdays[. != "0"]" -o "*" -b \
			-o " " \
			-o "root /etc/mail/sendreport" \
			${configxml_file} | /usr/local/bin/xml unesc >> ${cron_config}
	fi

	# Additional cron jobs
	if [ 0 -lt `configxml_get_count "//cron/job[enable]"` ]; then
		echo "# Additional cron jobs." >> ${cron_config}
		/usr/local/bin/xml sel -t -m "//cron/job[enable]" \
			-i "all_mins[. = "0"]" -m minute -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_mins[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_hours[. = "0"]" -m hour -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_hours[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_days[. = "0"]" -m day -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_days[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_months[. = "0"]" -m month -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_months[. != "0"]" -o "*" -b \
			-o " " \
			-i "all_weekdays[. = "0"]" -m weekday -i "position() > 1" -o "," -b -v "." -b -b \
			-i "all_weekdays[. != "0"]" -o "*" -b \
			-v "concat(' ',who,' ',command)" -n \
			${configxml_file} | /usr/local/bin/xml unesc >> ${cron_config}
	fi
}

load_rc_config $name
if checkyesno cron_dst
then
	cron_flags="$cron_flags -s"
fi
run_rc_command "$1"
