#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/DAEMON,v 1.5.14.1 2008/01/28 07:58:31 dougb Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS CONFIG

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
