#!/bin/sh
# Copyright (c) 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: fsck
# REQUIRE: CONFIG
# BEFORE:  mountcritlocal
# KEYWORD: nojail

. /etc/rc.subr

name="fsck"
start_cmd="fsck_start"
stop_cmd=":"

fsck_start()
{
	if [ "$autoboot" = no ]; then
		echo "Fast boot: skipping disk checks."
	elif [ "$autoboot" = yes ]; then
		echo "Starting file system checks:"
		eval /etc/rc.d.php/${name}
	fi
}

load_rc_config ${name}
run_rc_command "$1"
