#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: fstab
# BEFORE: CONFIG
# KEYWORD: nostart

. /etc/configxml.subr

# Defaults
fstab=${fstab:-"/etc/fstab"}
fstab_tmp=${fstab_tmp:-"/tmp/fstab"}

echo "Updating /etc/fstab."

# Copy the first line from the origin file.
/usr/bin/head -n 1 ${fstab} > ${fstab_tmp}

# Get number of configured mount points.
_index=`/usr/local/bin/xml sel -t -v "count(//mounts/mount)" ${configxml_file}`
while [ ${_index} -gt 0 ]
do
	# Get filesystem type.
	_fstype=`/usr/local/bin/xml sel -t -v "//mounts/mount[${_index}]/fstype" ${configxml_file}`
	_options=""
	_dump="0"
	_pass="0"

	# Set mount parameters.
	case ${_fstype} in
		[uU][fF][sS])
			_options="rw,acls";
			_pass="2";
			;;
		[mM][sS][dD][oO][sS][fF][sS])
			_options="rw";
			;;
		[cC][dD]9660)
			_options="ro,noauto";
			;;
		[nN][tT][fF][sS])
			_options="rw";
			;;
		[eE][xX][tT]2[fF][sS])
			_options="rw";
			;;
	esac

	/usr/local/bin/xml sel -t -m "//mounts/mount[${_index}]" \
		-v "concat(fullname,' /mnt/',sharename,' ',fstype,' ${_options} ${_dump} ${_pass}')" \
		${configxml_file} >> ${fstab_tmp}

	_index=$(( ${_index} - 1 ))
done

# Copy temporary file to origin location.
/bin/mv -f ${fstab_tmp} ${fstab}
