#!/bin/sh
# Copyright (c) 2008 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: geom
# REQUIRE: CONFIG
# BEFORE: disks
# KEYWORD: nojail shutdown

. /etc/rc.subr
. /etc/configxml.subr

name="geom"

# Custom commands
start_cmd="geom_start"
stop_cmd="geom_stop"

# Defaults
geom_load_param=${geom_load_param:-""}
geom_stop_param=${geom_stop_param:-""}

geom_start()
{
	local _classes _class

	_classes=$*
	_classes=${_classes:-"vinum mirror stripe concat raid5"}

	echo "Starting GEOM classes."
	for _class in ${_classes}; do
		case ${_class} in
			vinum)
				_geom_start_vinum;;
			*)
				_geom_load ${_class};;
		esac
	done

	_geom_raid5_tune
}

geom_stop()
{
	local _classes _class

	_classes=$*
	_classes=${_classes:-"vinum mirror stripe concat raid5"}

	echo "Stopping GEOM classes."
	for _class in ${_classes}; do
		_geom_stop ${_class}
	done
}

_geom_load()
{
	local _class

	_class=$1

	if configxml_isset //disks/disk/[class = 'g${_class}']; then
		/sbin/kldstat -q -m g_${_class} || /sbin/geom ${_class} load ${geom_load_param}
	fi
}

_geom_start_vinum()
{
	local _name

	/usr/local/bin/xml sel -t -m "//disks/disk/[class = 'gvinum']" \
		-v "name" \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _name; do
			/sbin/gvinum start "${_name}"
		done
}

_geom_stop()
{
	local _class _name

	_class=$1

	/usr/local/bin/xml sel -t -m "//disks/disk/[class = 'g${_class}']" \
		-v "name" \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _name; do
			/sbin/geom ${_class} status 1>/dev/null 2>&1 && /sbin/g${_class} stop ${geom_stop_param} "${_name}"
		done

	/sbin/kldstat -q -m g_${_class} && /sbin/geom ${_class} unload
}

# Optimize geom raid5 RAM usage
_geom_raid5_tune()
{
	local _realmem

	if configxml_isset //graid5/vdisk; then
		_realmem=`/sbin/sysctl -n hw.realmem`
		_realmem=`expr -- ${_realmem} / 1024 / 1024`

		if [ 128 -gt ${_realmem} ]; then
			/usr/bin/logger "Optimizing graid5 for systems with <= 128MB of RAM"
			sysctl kern.geom.raid5.maxwql=10
			sysctl kern.geom.raid5.maxmem=1100000
		elif [ 256 -gt ${_realmem} ]; then
			/usr/bin/logger "Optimizing graid5 for systems with <= 256MB of RAM"
			sysctl kern.geom.raid5.maxwql=20
			sysctl kern.geom.raid5.maxmem=2000000
		else
			/usr/bin/logger "Detected >= 512MB of RAM... No need to optimize RAM usage for GEOM raid5."
		fi

		# Modify ATA timeout to 15 seconds
		sysctl hw.ata.to=15
	fi
}

load_rc_config $name
run_rc_command "$@"
