#!/bin/sh
# Copyright (c) 2008 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: geom
# REQUIRE: CONFIG
# BEFORE: disks
# KEYWORD: nojail shutdown

. /etc/rc.subr
. /etc/configxml.subr

name="geom"

# Custom commands
start_cmd="geom_start"
stop_cmd="geom_stop"

# Defaults
geom_load_param=${geom_load_param:-""}
geom_stop_param=${geom_stop_param:-""}

geom_start()
{
	local _classes _class

	_classes=$*
	_classes=${_classes:-"vinum mirror stripe concat raid5"}

	echo "Starting GEOM classes."
	for _class in ${_classes}; do
		case ${_class} in
			vinum)
				_geom_start_vinum;;
			*)
				_geom_load ${_class};;
		esac
	done
}

geom_stop()
{
	local _classes _class

	_classes=$*
	_classes=${_classes:-"vinum mirror stripe concat raid5"}

	echo "Stopping GEOM classes."
	for _class in ${_classes}; do
		_geom_stop ${_class}
	done
}

_geom_load()
{
	local _class

	_class=$1

	if configxml_isset //g${_class}/vdisk; then
		/sbin/kldstat -q -m g_${_class} || /sbin/geom ${_class} load ${geom_load_param}
	fi
}

_geom_start_vinum()
{
	local _name

	/usr/local/bin/xml sel -t -m "//gvinum/vdisk" \
		-v "name" \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _name; do
			/sbin/gvinum start "${_name}"
		done
}

_geom_stop()
{
	local _class _name

	_class=$1

	/usr/local/bin/xml sel -t -m "//g${_class}/vdisk" \
		-v "name" \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _name; do
			/sbin/geom ${_class} status 1>/dev/null 2>&1 && /sbin/g${_class} stop ${geom_stop_param} "${_name}"
		done

	/sbin/kldstat -q -m g_${_class} && /sbin/geom ${_class} unload
}

load_rc_config $name
run_rc_command "$@"
