#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: htpasswd
# BEFORE: CONFIG

. /etc/rc.subr
. /etc/configxml.subr

# Defaults
htpasswd=${htpasswd:-"/var/run/.htpasswd"}

echo "Generating .htpasswd."

# Generate the /var/run/.htpasswd file used by lighttpd.
/usr/local/bin/xml sel -t \
	-i "string-length(//system/username) > 0" -v //system/username -b \
	-i "string-length(//system/username) = 0" -o "admin" -b \
	-v "concat(':',//system/password)" \
	${configxml_file} > ${htpasswd}

/bin/chmod 0600 ${htpasswd}
