#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: htpasswd
# BEFORE: CONFIG
# KEYWORD: nostart

. /etc/configxml.subr

# Defaults
htpasswd=${htpasswd:-"/var/run/.htpasswd"}

echo "Generating .htpasswd."

# Generate the /var/run/.htpasswd file used by lighttpd.
/usr/local/bin/xml sel -t -m "//system" \
	-i "string-length(username) > 0)" -v username -b \
	-i "string-length(username) = 0)" -o "admin" -b \
	-v "concat(':',password)" -n \
	${configxml_file} > ${htpasswd}

/bin/chmod 0600 ${htpasswd}
