#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: inadyn
# REQUIRE: DAEMON
# KEYWORD: shutdown

inadyn_enable=${inadyn_enable-"NO"}

. /etc/rc.subr
. /etc/conf.subr

name="inadyn"
rcvar=`set_rcvar`
inadyn_config=${inadyn_config:-"/var/etc/${name}.conf"}
required_files=${inadyn_config}
command="/usr/local/bin/${name}"
command_args="--input_file ${inadyn_config}"
start_precmd="start_precmd"

start_precmd()
{
	# Create .conf file
	create_conf_file ${name}
}

load_rc_config ${name}
run_rc_command "$1"
