#!/bin/sh

# PROVIDE: iscsi_target
# REQUIRE: NETWORKING
# XQUERY: -i "count(//iscsitarget/target) > 0" -o "0" -b
# RCVAR: iscsi_target

. /etc/rc.subr
. /etc/configxml.subr

name="iscsi_target"
rcvar=`set_rcvar`

# Custom commands
start_precmd="create_conf"

# Defaults
iscsi_target_enable=${iscsi_target_enable:-"NO"}
iscsi_target_config="/var/etc/iscsi/targets"
iscsi_target_auths="/var/etc/iscsi/auths"
iscsi_target_passwd="/var/etc/iscsi/passwd"
command="/usr/local/bin/iscsi-target"
command_args="-f ${iscsi_target_config}"
pidfile="/var/run/iscsi-target.pid"

create_conf()
{
	# Clear existing file.
	cat /dev/null > ${iscsi_target_config}

	# Create passwd and auths file if necessary.
	if [ ! -e ${iscsi_target_auths} ]; then
		cat /dev/null > ${iscsi_target_auths}
	fi
	if [ ! -e ${iscsi_target_passwd} ]; then
		cat /dev/null > ${iscsi_target_passwd}
	fi

	# Iterate over all extent/device/target attributes.
	/usr/local/bin/xml sel -t \
		-o "# extents" -n \
		-m "//iscsitarget/extent" \
			-v "concat(name,' ',path,name,' 0 ',size,'MB')" -n \
		-b \
		-n -o "# devices" -n \
		-m "//iscsitarget/device" \
			-v "concat(name,' ',type,' ')" \
			-m "storage" \
				-v "concat(.,' ')" \
			-b -n \
		-b \
		-n -o "# targets" -n \
		-m "//iscsitarget/target" \
			-v "concat(name,' ',flags,' ')"  \
			-m "storage" \
				-v "concat(.,' ')" \
			-b \
			-v "concat(ipaddr,'/',subnet)" -n \
		-b \
		${configxml_file} | /usr/local/bin/xml unesc >> ${iscsi_target_config}
}

load_rc_config ${name}
run_rc_command "$1"
