#!/bin/sh

# PROVIDE: iscsi_target
# REQUIRE: NETWORKING

. /etc/rc.subr
. /etc/rc.subrconf

name="iscsi_target"
rcvar=`set_rcvar`

command="/usr/local/bin/iscsi-target"
required_files="/usr/local/etc/iscsi/targets"
pidfile="/var/run/iscsi-target.pid"

load_rc_config $name

: ${iscsi_target_enable="NO"}
: ${iscsi_target_config="/var/etc/iscsi/targets"}

command_args="-f $iscsi_target_config"

create_conf_file ${name}
run_rc_command "$1"
