#!/bin/sh

# PROVIDE: lighttpd
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr
. /etc/conf.subr

name="lighttpd"
rcvar=`set_rcvar`

load_rc_config ${name}

: ${lighttpd_enable="NO"}
: ${lighttpd_conf="/var/etc/lighttpd.conf"}

command=/usr/local/sbin/lighttpd
command_args="-f ${lighttpd_conf} -m /usr/local/lib/lighttpd"
pidfile=/var/run/lighttpd.pid
required_files=${lighttpd_conf}
start_precmd="start_precmd"
stop_postcmd=stop_postcmd
restart_precmd="checkconfig"
reload_precmd=reload_precmd
reload_postcmd=reload_postcmd
sig_reload="-INT"
check_cmd="checkconfig"
extra_commands="reload check"

start_precmd()
{
	# Create .conf file
	create_conf_file ${name}
}

checkconfig()
{
	echo "Performing sanity check on ${name} configuration:"
	eval "${command} ${command_args} -t"
}

stop_postcmd()
{
	rm -f ${pidfile}
}

reload_precmd()
{
	echo "Stoping ${name} and start gracefully."
}

reload_postcmd()
{
	rm -f ${pidfile}
	run_rc_command start
}

run_rc_command "$1"
