#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: mdnsresponder
# REQUIRE: DAEMON
# KEYWORD: shutdown
# XPATH: //system/zeroconf

. /etc/rc.subr
. /etc/conf.subr

name="mdnsresponder"
rcvar=`set_rcvar`
mdnsresponder_config=${mdnsresponder_config:-"/var/etc/${name}.conf"}
required_files=${mdnsresponder_config}
command="/usr/local/sbin/mDNSResponderPosix"
command_args="-b -f ${mdnsresponder_config}"
pidfile="/var/run/mDNSResponder.pid"

load_rc_config ${name}
create_conf_file ${name}
run_rc_command "$1"
