#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: msntp
# REQUIRE: DAEMON

. /etc/rc.subr
. /etc/configxml.subr

name="msntp"
rcvar=`set_rcvar`

# Custom commands
start_cmd="start_cmd"
stop_cmd="stop_cmd"

# Defaults
msntp_enable="${msntp_enable:=NO}"
pidfile="/var/run/${name}.pid"
scriptpidfile="/var/run/runmsntp.pid"

start_cmd()
{
	local _cmdarg

	echo "Starting ${name}."

	# Get command attributes from config file.
	_cmdarg=`/usr/local/bin/xml sel -t \
		-v "concat(//system/time-update-interval,' ',//system/timeservers)" \
		${configxml_file}`

	nohup /usr/local/bin/runmsntp.sh ${scriptpidfile} ${pidfile} ${_cmdarg} > /dev/null 2>&1 &
}

stop_cmd()
{
	echo "Stopping ${name}."

	# Kill runmsntp script.
	/bin/kill -s TERM `/bin/cat ${scriptpidfile}`
	rm -r ${scriptpidfile}

	# Kill msntp.
	/bin/kill -s TERM `/bin/cat ${pidfile}`
	rm -r ${pidfile}
}

load_rc_config ${name}
run_rc_command "$1"
