#!/bin/sh
# Copyright (c) 2007-2008 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: netif
# REQUIRE: cleanvar mountcritlocal pccard sysctl
# KEYWORD: nojail

. /etc/rc.subr
. /etc/network.subr
. /etc/configxml.subr

name="network"
start_cmd="network_start"
stop_cmd=":"
cloneup_cmd="clone_up"
clonedown_cmd="clone_down"
cloneup_precmd="clone_conf"
clonedown_precmd="clone_conf"
extra_commands="cloneup clonedown"

network_start()
{
	# Create cloned interfaces
	clone_up

	local _result
	# Bring up network interfaces
	eval /etc/rc.d.php/netif
	_result=$?

	# Display interfaces configured by this script
	/sbin/ifconfig

	return ${_result}
}

clone_conf()
{
	local _id _ipaddr _subnet _if _cloned_interfaces

	# Update rc.conf.
	_cloned_interfaces=`/usr/local/bin/xml sel -t -m "//vlans/vlan" \
		-v "concat('vlan',id,' ')" \
		${configxml_file} | /usr/local/bin/xml unesc`
	eval /usr/local/sbin/rconf attribute set "cloned_interfaces" "${_cloned_interfaces}"	

	/usr/local/bin/xml sel -t -m "//vlans/vlan" \
		-v "concat(id,' ',ipaddr,' ',subnet,' ',if)" \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _id _ipaddr _subnet _if; do
			eval /usr/local/sbin/rconf attribute set "ifconfig_vlan${_id}" "inet ${_ipaddr}/${_subnet} vlan ${_id} vlandev ${_if}"
		done
}

load_rc_config ${name}
run_rc_command "$1"
