#!/bin/sh

# PROVIDE: NETWORKING NETWORK
# REQUIRE: CONFIG
# REQUIRE: netif netoptions routing network_ipv6
# REQUIRE: resolv

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
