#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/NETWORKING,v 1.13.4.1 2008/01/28 07:58:31 dougb Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
#

# PROVIDE: NETWORKING NETWORK
# REQUIRE: CONFIG
# REQUIRE: netif netoptions routing network_ipv6
# REQUIRE: resolv

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
