#!/bin/sh
#
# $FreeBSD: stable/9/etc/rc.d/nfscbd 193354 2009-06-02 22:15:47Z rmacklem $
#

# PROVIDE: nfscbd
# REQUIRE: NETWORKING nfsuserd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfscbd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
