#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/nfsd,v 1.13.10.2.2.1 2009/04/15 03:14:26 kensmith Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
# - Add /sbin/ to sysctl calls, otherwise script execution fails via WebGUI.
#

# PROVIDE: nfsd
# REQUIRE: mountd
# KEYWORD: nojail shutdown
# XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
# RCVAR: nfs_server

. /etc/rc.subr
. /etc/configxml.subr

name="nfsd"
rcvar=`set_rcvar nfs_server`
command="/usr/sbin/${name}"

# Customize number of server processes/daemons
nfs_server_flags=`/usr/local/bin/xml sel -t -v "concat('-u -t -n ',//nfsd/numproc)" ${configxml_file} | /usr/local/bin/xml unesc`

load_rc_config $name
command_args="${nfs_server_flags}"
start_precmd="nfsd_precmd"
sig_stop="USR1"

nfsd_precmd()
{
	if ! /sbin/sysctl vfs.nfsrv >/dev/null 2>&1; then
		force_depend nfsserver || return 1
	fi

	if ! checkyesno rpcbind_enable  && \
	    ! /etc/rc.d/rpcbind forcestatus 1>/dev/null 2>&1
	then
		force_depend rpcbind || return 1
	fi

	if ! checkyesno mountd_enable  && \
	    ! /etc/rc.d/mountd forcestatus 1>/dev/null 2>&1
	then
		force_depend mountd || return 1
	fi

	if checkyesno nfs_reserved_port_only; then
		echo 'NFS on reserved port only=YES'
		/sbin/sysctl vfs.nfsrv.nfs_privport=1 > /dev/null
	fi
	return 0
}

run_rc_command "$1"
