#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: pam
# BEFORE: CONFIG
# REQUIRE: system_postinit

#
# Configure PAM, NSS and LDAP modules
#

. /etc/configxml.subr

# Defaults
system_config=${system_config:-"/etc/pam.d/system"}
sshd_config=${sshd_config:-"/etc/pam.d/sshd"}
ftp_config=${ftp_config:-"/etc/pam.d/ftp"}
login_config=${login_config:-"/etc/pam.d/login"}
nsswitch_config=${nsswitch_config:-"/etc/nsswitch.conf"}
ldap_config=${ldap_config:-"/var/etc/ldap.conf"}
ldap_secret=${ldap_secret:-"/var/etc/ldap.secret"}

# Ensure that target directory exists.
if [ ! -e /var/etc/pam.d ]; then
	/bin/mkdir -m 0744 /var/etc/pam.d
fi

# Create /var/etc/pam.d/system.
/usr/local/bin/xml sel -t \
	-o "# System-wide defaults" -n \
	-n \
	-o "# auth" -n \
	-o "auth       sufficient   pam_opie.so             no_warn no_fake_prompts" -n \
	-o "auth       requisite    pam_opieaccess.so       no_warn allow_local" -n \
	-i "count(//ad/enable) > 0" \
		-o "#auth       sufficient   /usr/local/lib/pam_winbind.so	debug try_first_pass" -n \
	-b \
	-i "count(//ldap/enable) > 0" \
		-o "#auth       sufficient   /usr/local/lib/pam_ldap.so	no_warn try_first_pass" -n \
	-b \
	-o "auth       required     pam_unix.so             no_warn try_first_pass nullok" -n \
	-n -o "# account" -n \
	-i "count(//ad/enable) > 0" \
		-o "#account    sufficient   /usr/local/lib/pam_winbind.so" -n \
	-b \
	-o "account    required     pam_login_access.so" -n \
	-o "account    required     pam_unix.so" -n \
	-n -o "# session" -n \
	-o "session    required     pam_lastlog.so          no_fail" -n \
	-n -o "# password" -n \
	-i "count(//ad/enable) > 0" \
		-o "#password   sufficient   /usr/local/lib/pam_winbind.so	debug try_first_pass" -n \
	-b \
	-o "password   required     pam_unix.so             no_warn try_first_pass" \
	${configxml_file} > ${system_config}

# Create /var/etc/pam.d/sshd.
/usr/local/bin/xml sel -t \
	-o "# PAM configuration for the sshd service" -n \
	-n \
	-o "# auth" -n \
	-o "auth       required        pam_nologin.so          no_warn" -n \
	-o "auth       sufficient      pam_opie.so             no_warn no_fake_prompts" -n \
	-o "auth       requisite       pam_opieaccess.so       no_warn allow_local" -n \
	-i "count(//ad/enable) > 0" \
		-o "auth       sufficient      /usr/local/lib/pam_winbind.so	debug try_first_pass" -n \
	-b \
	-i "count(//ldap/enable) > 0" \
		-o "auth       sufficient      /usr/local/lib/pam_ldap.so	no_warn try_first_pass" -n \
	-b \
	-o "auth       required        pam_unix.so             no_warn try_first_pass" -n \
	-n -o "# account" -n \
	-i "count(//ad/enable) > 0" \
		-o "account    sufficient		/usr/local/lib/pam_winbind.so" -n \
	-b \
	-o "account    required        pam_unix.so" -n \
	-n -o "# session" -n \
	-o "session    required        pam_permit.so" -n \
	-n -o "# password" -n \
	-i "count(//ad/enable) > 0" \
		-o "password   sufficient	/usr/local/lib/pam_winbind.so	debug try_first_pass" -n \
	-b \
	-o "password   required        pam_unix.so             no_warn try_first_pass" \
	${configxml_file} > ${sshd_config}

# Create /var/etc/pam.d/ftp.
/usr/local/bin/xml sel -t \
	-o "# PAM configuration for the ftpd service" -n \
	-n \
	-o "# auth" -n \
	-o "auth       required        pam_nologin.so          no_warn" -n \
	-o "auth       sufficient      pam_opie.so             no_warn no_fake_prompts" -n \
	-o "auth       requisite       pam_opieaccess.so       no_warn allow_local" -n \
	-i "count(//ad/enable) > 0" \
		-o "auth       sufficient      /usr/local/lib/pam_winbind.so	debug try_first_pass" -n \
	-b \
	-i "count(//ldap/enable) > 0" \
		-o "auth       sufficient      /usr/local/lib/pam_ldap.so	no_warn try_first_pass" -n \
	-b \
	-o "auth       required        pam_unix.so             no_warn try_first_pass" -n \
	-n -o "# account" -n \
	-i "count(//ad/enable) > 0" \
		-o "account    sufficient	/usr/local/lib/pam_winbind.so" -n \
	-b \
	-o "account    required        pam_login_access.so" -n \
	-o "account    required        pam_unix.so" -n \
	-n -o "# session" -n \
	-o "session    required        pam_permit.so" \
	${configxml_file} > ${ftp_config}

# Create /var/etc/pam.d/login.
/usr/local/bin/xml sel -t \
	-o "# PAM configuration for the login service" -n \
	-n \
	-o "# auth" -n \
	-o "auth       required        pam_nologin.so          no_warn" -n \
	-i "count(//ad/enable) > 0" \
		-o "auth       sufficient      /usr/local/lib/pam_winbind.so	debug try_first_pass" -n \
	-b \
	-i "count(//ldap/enable) > 0" \
		-o "auth       sufficient      /usr/local/lib/pam_ldap.so	no_warn try_first_pass" -n \
	-b \
	-o "auth       sufficient      pam_self.so	no_warn" -n \
	-o "auth       include         system" -n \
	-n -o "# account" -n \
	-i "count(//ad/enable) > 0" \
		-o "account    sufficient	/usr/local/lib/pam_winbind.so" -n \
	-b \
	-o "account    requisite       pam_securetty.so" -n \
	-o "account    include         system" -n \
	-n -o "# session" -n \
	-o "session    include         system" -n \
	-n -o "# password" -n \
	-o "password   include         system" \
	${configxml_file} > ${login_config}

# Create /var/etc/nsswitch.conf
/usr/local/bin/xml sel -t \
	-i "count(//ad/enable) > 0" -i "count(//ldap/enable) = 0" \
		-o "group: files winbind" -n \
		-o "group_compat: nis" -n \
		-o "hosts: files dns wins" -n \
		-o "networks: files" -n \
		-o "passwd: files winbind" -n \
		-o "passwd_compat: nis" -n \
		-o "shells: files" \
	-b -b \
	-i "count(//ad/enable) > 0" -i "count(//ldap/enable) > 0" \
		-o "group: files winbind ldap" -n \
		-o "group_compat: nis" -n \
		-o "hosts: files dns wins ldap" -n \
		-o "networks: files" -n \
		-o "passwd: files winbind ldap" -n \
		-o "passwd_compat: nis" -n \
		-o "shells: files" \
	-b -b \
	-i "count(//ad/enable) = 0" -i "count(//ldap/enable) > 0" \
		-o "group: files ldap" -n \
		-o "group_compat: nis" -n \
		-o "hosts: files dns ldap" -n \
		-o "networks: files" -n \
		-o "passwd: files ldap" -n \
		-o "passwd_compat: nis" -n \
		-o "shells: files" \
	-b -b \
	-i "count(//ad/enable) = 0" -i "count(//ldap/enable) = 0" \
		-o "group: compat" -n \
		-o "group_compat: nis" -n \
		-o "hosts: files dns" -n \
		-o "networks: files" -n \
		-o "passwd: compat" -n \
		-o "passwd_compat: nis" -n \
		-o "shells: files" \
	-b -b \
	${configxml_file} > ${nsswitch_config}

# Create /var/etc/ldap.conf and /var/etc/ldap.secret
if configxml_isset //ldap/enable; then
	/usr/local/bin/xml sel -t -m "//ldap" \
		-v "concat('uri ldap://',host_ip)" -n \
		-v "concat('base ',base)" -n \
		-v "concat('binddn ',binddn)" -n \
		-v "concat('bindpw ',bindpw)" -n \
		-v "concat('nss_base_passwd ',password_suffix,'?one')" -n \
		-v "concat('nss_base_shadow ',password_suffix,'?one')" -n \
		-v "concat('nss_base_group ',group_suffix,'?one')" -n \
		-v "concat('pam_password ',pam_password)" \
		${configxml_file} > ${ldap_config}

	/usr/local/bin/xml sel -t -m "//ldap" \
		-v "password_suffix" \
		${configxml_file} > ${ldap_secret}

	/bin/chmod 0600 ${ldap_secret}
fi
