#!/bin/sh

# PROVIDE: powerd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail
# XPATH: //system/powerd
# RCVAR: powerd

powerd_enable=${powerd_enable:-"NO"}

. /etc/rc.subr

name="powerd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
command_args="-a adaptive -b adaptive"
stop_postcmd=powerd_poststop

powerd_poststop()
{
	/sbin/sysctl dev.cpu.0.freq=`/sbin/sysctl -n dev.cpu.0.freq_levels | /usr/bin/sed -e 's:/.*::'` > /dev/null
}

load_rc_config $name
run_rc_command "$1"
