#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/quota,v 1.5.2.1 2008/01/28 08:22:33 dougb Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
# Changes:
# - Replace 'mountcritremote' requirement
#

# Enable/Check the quotas (must be after ypbind if using NIS)

# PROVIDE: quota
# REQUIRE: NETWORKING FILESYSTEMS cleanvar
# BEFORE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="quota"
rcvar="enable_quotas"
start_cmd="quota_start"
stop_cmd="/usr/sbin/quotaoff -a"

quota_start()
{
	if checkyesno check_quotas; then
		echo -n 'Checking quotas:'
		quotacheck -a
		echo ' done.'
	fi

	echo -n 'Enabling quotas:'
	quotaon -a
	echo ' done.'
}

load_rc_config $name
run_rc_command "$1"
