#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: rcconf

. /etc/rc.subr
. /etc/conf.subr

name="rcconf"
stop_cmd=":"
start_cmd=":"

load_rc_config ${name}
create_conf_file ${name}
run_rc_command "$1"
