#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: rcconf

. /etc/rc.subr

name="rcconf"
stop_cmd=":"
start_cmd="start_cmd"

start_cmd()
{
	echo "Updating rc.conf."
	# Update rc.conf file. Use settings from config.xml.
	eval "/etc/rc.d.php/${name}"
	return $?
}

load_rc_config ${name}
run_rc_command "$1"
