#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rpcbind,v 1.12.14.1 2008/01/28 07:58:31 dougb Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING syslogd
# XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
# RCVAR: rpcbind

. /etc/rc.subr

name="rpcbind"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
