#!/bin/sh
#
# $NetBSD: rpcbind,v 1.6 2002/01/31 01:26:06 lukem Exp $
# $FreeBSD: src/etc/rc.d/rpcbind,v 1.12 2004/10/07 13:55:26 mtm Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING syslogd
# KEYWORD: nostart
# XPATH: //nfs/enable

. /etc/rc.subr

name="rpcbind"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
