#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rpcbind,v 1.12.10.2.2.1 2009/04/15 03:14:26 kensmith Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
# Changes:
# - Remove useless requirements
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd
# KEYWORD: shutdown
# XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
# RCVAR: rpcbind

. /etc/rc.subr

name="rpcbind"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
