#!/bin/sh
# Copyright (c) 2007-2008 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: rsyncd
# REQUIRE: DAEMON
# KEYWORD: shutdown
# XQUERY: -i "count(//rsyncd/enable) > 0" -o "0" -b
# RCVAR: rsyncd

. /etc/rc.subr
. /etc/configxml.subr

name="rsyncd"
rcvar=`set_rcvar`

# Custom commands
start_precmd="create_conf"

# Defaults
rsyncd_enable=${rsyncd_enable:-"NO"}
rsyncd_config=${rsyncd_config:-"/var/etc/${name}.conf"}
rsyncd_motd=${rsyncd_motd:-"/var/etc/rsyncd.motd"}
command="/usr/local/bin/rsync"
command_args="--daemon --config=${rsyncd_config}"
pidfile="/var/run/${name}.pid"

create_conf()
{
	local _motd

	# Create rsyncd.conf file.
	/usr/local/bin/xml sel -t -m "//rsyncd" \
		-o "syslog facility = local4" -n \
		-o "list = no" -n \
		-v "concat('port = ',port)" -n \
		-o "pid file = ${pidfile}" -n \
		-i "string-length(maxcon) > 0" -v "concat('max connections = ',maxcon)" -n -b \
		-i "string-length(motd) > 0" -o "motd file = ${rsyncd_motd}" -n -b \
		-i "count(rsyncd_user) > 0" -v "concat('uid = ',rsyncd_user)" -n -b \
		-m "share" \
			-n \
			-v "concat('[',name,']')" -n \
			-v "concat('comment = ',comment)" -n \
			-v "concat('path = ',path)" -n \
			-i "count(browseable) > 0" -o "list = true" -n -b \
			-i "string-length(maxconnections) > 0" -v "concat('max connections = ',maxconnections)" -n -b \
			-o "read only = false" -n \
			-i "rwmode[. = 'ro']" -o "read only = true" -n -b \
			-i "rwmode[. = 'wo']" -o "write only = true" -n -b \
			-i "string-length(hostsallow) > 0" \
				-v "concat('hosts allow = ',hostsallow)" -n -b \
			-i "string-length(hostsdeny) > 0" \
				-v "concat('hosts deny = ',hostsdeny)" -n -b \
		-b \
		${configxml_file} | /usr/local/bin/xml unesc > ${rsyncd_config}

	# Create MOTD file.
	_motd=`configxml_get "//rsyncd/motd"`
	if [ -n "${_motd}" ]; then
		echo "${_motd}" > ${rsyncd_motd}
	fi
}

load_rc_config $name
run_rc_command "$1"
