#!/bin/sh
# Copyright (c) 2007-2008 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: rsync_client
# REQUIRE: DAEMON
# BEFORE: cron

. /etc/rc.subr
. /etc/configxml.subr

name="rsync_client"

load_rc_config $name

# Defaults
rsync_logfile=${rsync_logfile:-"/var/log/${name}.log"}

# Get number of scripts to generate
_scriptnum=`configxml_get_count "//rsync/rsyncclient"`

if [ 0 -lt ${_scriptnum} ]; then
	echo "Generating client rsyncd cron scripts."

	_i=0
	while [ ${_scriptnum} -gt 0 ]
	do
		# Set scriptname
		_rsyncscript=/var/run/rsync_client${_i}.sh

		# Generate the shell script used by cron
		/usr/local/bin/xml sel -t -m "//rsync/rsyncclient[position()=${_scriptnum}]" \
			-o "#!/bin/sh" -n \
			-v "concat('/usr/bin/logger -p local4.notice &quot;Start of remote RSYNC synchronization from ',remoteshare,' on ',rsyncserverip,' to ',localshare,'&quot;')" -n \
			-o "if [ -r /var/run/rsync_client-running${_i} ]; then" -n \
			-o "/usr/bin/logger -p local4.notice &quot;Previous client synchronization still running... exiting&quot;" -n \
			-o "exit" -n \
			-o "fi" -n \
			-o "/usr/bin/touch /var/run/rsync_client-running${_i}" -n \
			-o "/usr/local/bin/rsync -rtz --log-file=${rsync_logfile} " \
			-m "options" \
				-i "count(delete) > 0" -o "--delete --delete-after " -b \
				-i "count(quiet) > 0" -o "--quiet " -b \
			-b \
			-i "contains(rsyncserverip,'.')" \
				-v "concat('&quot;rsync://',rsyncserverip,'/',remoteshare,'&quot; &quot;',localshare,'&quot;')" -n \
			-b \
			-i "contains(rsyncserverip,':')" \
				-v "concat('&quot;rsync://\\[',rsyncserverip,'\\]/',remoteshare,'&quot; &quot;',localshare,'&quot;')" -n \
			-b \
			-o "/bin/rm -f /var/run/rsync_client-running${_i}" -n \
			-v "concat('/usr/bin/logger -p local4.notice &quot;End of remote RSYNC synchronization from ',remoteshare,' on ',rsyncserverip,' to ',localshare,'&quot;')" \
			${configxml_file} | /usr/local/bin/xml unesc > ${_rsyncscript}

		# Add execute right to the script
		/bin/chmod 0770 ${_rsyncscript}

		_i=$(( ${_i} + 1 ))
		_scriptnum=$(( ${_scriptnum} - 1 ))
	done
fi
