#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: rsync_client
# REQUIRE: DAEMON
# BEFORE: cron

. /etc/configxml.subr

# Get number of scripts to generate.
_scriptnum=`/usr/local/bin/xml sel -t -v "count(//rsync/rsyncclient)" ${configxml_file}`

if [ 0 -lt ${_scriptnum} ]; then
	echo "Generating client rsyncd cron scripts."

	_i=0
	while [ ${_scriptnum} -gt 0 ]
	do
		# Set scriptname.
		_rsyncscript=/var/run/rsync_client${_i}.sh

		# Generate the shell script that is used by cron.
		/usr/local/bin/xml sel -t -m "//rsync/rsyncclient[position()=${_scriptnum}]" \
			-o "#!/bin/sh" -n \
			-v "concat('/usr/bin/logger -p local4.notice &quot;Start of remote RSYNC synchronization from share ',remoteshare,' on ',rsyncserverip,' to ',localshare,'&quot;')" -n \
			-o "if [ -r /var/run/rsync_client-running${_i} ]; then" -n \
			-o "/usr/bin/logger -p local4.notice &quot;Previous client synchronization still running... exiting&quot;" -n \
			-o "exit" -n \
			-o "fi" -n \
			-o "/usr/bin/touch /var/run/rsync_client-running${_i}" -n \
			-o "/usr/local/bin/rsync -rtz " \
			-i "count(opt_delete) > 0" \
				-o "--delete --delete-after " \
			-b \
			-i "contains(rsyncserverip,'.')" \
				-v "concat('rsync://',rsyncserverip,'/',remoteshare,' /mnt/',localshare)" -n \
			-b \
			-i "contains(rsyncserverip,':')" \
				-v "concat('rsync://\\[',rsyncserverip,'\\]/',remoteshare,' /mnt/',localshare)" -n \
			-b \
			-o "/bin/rm -f /var/run/rsync_client-running${_i}" -n \
			-v "concat('/usr/bin/logger -p local4.notice &quot;End of remote RSYNC synchronization from share ',remoteshare,' on ',rsyncserverip,' to ',localshare,'&quot;')" \
			${configxml_file} > ${_rsyncscript}

		# Add exectutive right to the script.
		/bin/chmod 0770 ${_rsyncscript}

		_i=$(( ${_i} + 1 ))
		_scriptnum=$(( ${_scriptnum} - 1 ))
	done
fi
