#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/SERVERS,v 1.7.4.1 2008/01/28 07:58:31 dougb Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
#

# PROVIDE: SERVERS

#	This is a dummy dependency, for early-start servers relying on
#	some basic configuration.
