#!/bin/sh
# Copyright (c) 2006-2008 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: smartd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown
# XQUERY: -i "count(//smartd/enable) > 0 and count(//disks/disk[smart]) > 0" -o "0" -b
# RCVAR: smartd

. /etc/rc.subr
. /etc/configxml.subr

name="smartd"
rcvar=`set_rcvar`

# Custom commands
start_precmd="start_precmd"

# Defaults
smartd_enable=${smartd_enable:-"NO"}
smartd_conf=${smartd_conf:-"/var/etc/${name}.conf"}
pidfile="/var/run/${name}.pid"
command="/usr/local/sbin/smartd"
command_args="--configfile=${smartd_conf} --pidfile=${pidfile} --logfacility=local5"

start_precmd()
{
	local _devicespecialfile _type _selftest

	# Clear existing file
	/bin/cat /dev/null > ${smartd_conf}

	# Create configuration file
	/usr/local/bin/xml sel -t -m "//disks/disk[smart]" \
		-v "concat(devicespecialfile,' ',type)" \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _devicespecialfile _type; do
			case ${_type} in
				IDE)
					_type="ata";;
				SCSI)
					_type="scsi";;
			esac

			# Process scheduled self-tests.
			# Example: -s (O/../.././(00|06|12|18)|S/../.././01|L/../../6/03)
			_selftest=`/usr/local/bin/xml sel -t -m "//smartd/selftest[devicespecialfile = '${_devicespecialfile}']" \
				-i "count(//smartd/selftest) > 1 and position() = 1" -o "(" -b \
				-i "position() > 1" -o "|" -b \
				-v "concat(type,'/')" \
				-i "all_months[. = "0"]" \
					-i "count(month) > 1" -o "(" -b \
					-m month \
						-i "position() > 1" -o "|" -b \
						-v "." \
					-b \
					-i "count(month) > 1" -o ")" -b \
				-b \
				-i "all_months[. != "0"]" -o ".." -b \
				-o "/" \
				-i "all_days[. = "0"]" \
					-i "count(day) > 1" -o "(" -b \
					-m day \
						-i "position() > 1" -o "|" -b \
						-v "." \
					-b \
					-i "count(day) > 1" -o ")" -b \
				-b \
				-i "all_days[. != "0"]" -o ".." -b \
				-o "/" \
				-i "all_weekdays[. = "0"]" \
					-i "count(weekday) > 1" -o "(" -b \
					-m weekday \
						-i "position() > 1" -o "|" -b \
						-v "." \
					-b \
					-i "count(weekday) > 1" -o ")" -b \
				-b \
				-i "all_weekdays[. != "0"]" -o "." -b \
				-o "/" \
				-i "all_hours[. = "0"]" \
					-i "count(hour) > 1" -o "(" -b \
					-m hour \
						-i "position() > 1" -o "|" -b \
						-v "." \
					-b \
					-i "count(hour) > 1" -o ")" -b \
				-b \
				-i "all_hours[. != "0"]" -o ".." -b \
				-i "count(//smartd/selftest) > 1 and position() = last()" -o ")" -b \
				${configxml_file} | /usr/local/bin/xml unesc`
			if [ -n "${_selftest}" ]; then
				_selftest="-s ${_selftest}";
			fi

			echo "${_devicespecialfile} -a -d ${_type} ${_selftest}" >> ${smartd_conf}
		done
}

load_rc_config ${name}
run_rc_command "$1"
