#!/bin/sh
# Copyright (c) 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: smartd
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown
# XQUERY: -i "count(//system/smart) > 0" -o "0" -b
# RCVAR: smartd

smartd_enable=${smartd_enable:-"NO"}

. /etc/rc.subr

name="smartd"
rcvar=`set_rcvar`
pidfile="/var/run/${name}.pid"
command="/usr/local/sbin/smartd"
command_args="--pidfile=${pidfile} --logfacility=local5"

load_rc_config ${name}
run_rc_command "$1"
