#!/bin/sh
# Copyright (c) 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: snmpd
# REQUIRE: NETWORKING
# KEYWORD: nojail
# XQUERY: -i "count(//snmpd/enable) > 0" -o "0" -b
# RCVAR: snmpd

. /etc/rc.subr
. /etc/configxml.subr

name="snmpd"
rcvar=`set_rcvar`

# Custom commands
start_precmd="create_conf"

# Defaults
snmpd_enable=${snmpd_enable:-"NO"}
snmpd_config=${snmpd_config:-"/var/etc/${name}.conf"}
pidfile="/var/run/${name}.pid"
command="/usr/sbin/${name}"
command_args="-c ${snmpd_config} -P ${pidfile}"

create_conf()
{
	/usr/local/bin/xml sel -t -m "//snmpd" \
		-v "concat('syslocation ',syslocation)" -n \
		-v "concat('syscontact ',syscontact)" -n \
		-v "concat('rocommunity ',rocommunity)" -n \
		${configxml_file} | /usr/local/bin/xml unesc > ${snmpd_config}
}

load_rc_config ${name}
run_rc_command "$1"
