#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: system_postinit
# REQUIRE: system_init

# Let the other functions know we've finished booting.
rm -f /var/etc/booting > /dev/null 2>&1
