#!/bin/sh
# Copyright (c) 2007-2009 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: timezone
# BEFORE: CONFIG
# REQUIRE: SYSTEMINIT

. /etc/rc.subr
. /etc/configxml.subr

_timezone=`configxml_get "//system/timezone"`
if [ -z "${_timezone}" ]; then
	_timezone="Etc/UTC"
fi

/usr/bin/tar -xOf /usr/share/zoneinfo.tgz "./${_timezone}" > /etc/localtime
