#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: ushare
# REQUIRE: DAEMON
# KEYWORD: shutdown
# XQUERY: -i "count(//upnp/enable) > 0" -o "0" -b
# RCVAR: ushare

ushare_enable=${ushare_enable:-"NO"}

. /etc/rc.subr
. /etc/configxml.subr

name="ushare"
rcvar=`set_rcvar`

# Custom commands
start_precmd="create_conf"
stop_postcmd="stop_postcmd"

# Defaults
ushare_config=${ushare_config:-"/var/etc/${name}.conf"}
required_files=${ushare_config}
command="/usr/local/bin/${name}"
command_args="--daemon --xbox --dlna --cfg=${ushare_config}"

# Check if ushare web interface is disabled.
if ! configxml_isset //upnp/web; then
	command_args="${command_args} --no-web"
fi

# Clear existing config file.
cat /dev/null > ${ushare_config}

create_conf()
{
	local _if

	# Get interface used for uPnP.
	_if=`/usr/local/bin/xml sel -t -v "//upnp/if" ${configxml_file}`

	# Setup a multicast route for UPnP messages.
	/sbin/route add -net 239.0.0.0 -netmask 255.0.0.0 -interface ${_if}

	# Create config file.
	/usr/local/bin/xml sel -t -m "//upnp" \
		-v "concat('USHARE_NAME=',name)" -n \
		-v "concat('USHARE_IFACE=',if)" -n \
		-o "USHARE_OVERRIDE_ICONV_ERR=YES" -n \
		-i "string-length(port) > 0" -v "concat('USHARE_PORT=',port)" -n -b \
		-o "USHARE_DIR=" -m "//upnp/content" -v "concat(.,' ')" -b -n \
		${configxml_file} > ${ushare_config}
}

stop_postcmd()
{
	# Delete multicast route.
	/sbin/route delete -net 239.0.0.0 > /dev/null 2>&1
}

load_rc_config ${name}
run_rc_command "$1"
