#!/bin/sh
# Copyright © 2007 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: ushare
# REQUIRE: DAEMON
# KEYWORD: shutdown
# XPATH: //upnp/enable

ushare_enable=${ushare_enable-"NO"}

. /etc/rc.subr
. /etc/conf.subr

name="ushare"
rcvar=`set_rcvar`
ushare_config=${ushare_config:-"/var/etc/${name}.conf"}
required_files=${ushare_config}
command="/usr/local/bin/${name}"
command_args="--daemon --xbox --cfg=${ushare_config}"
stop_postcmd="stop_postcmd"

stop_postcmd()
{
	# Delete multicast route.
	/sbin/route delete -net 239.0.0.0 > /dev/null
}

load_rc_config ${name}
create_conf_file ${name}
run_rc_command "$1"
