#!/bin/sh
#
# Copyright (c) 1999  Matt Dillon
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD: src/etc/rc.d/var,v 1.40.2.4 2008/01/29 00:33:16 dougb Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
# Changes:
# - Remove useless code
# ToDo:
# - Relocate code to populate /var from /etc/rc to this file ASAP
# - Add customized mount_md function
#

# PROVIDE: var
# REQUIRE: FILESYSTEMS

. /etc/rc.subr

name="var"
stop_cmd=':'

load_rc_config $name

# Defaults
varmfs_root=${varmfs_root:-"/"}

# Provide a function for normalizing the mounting of memory
# filesystems. This function has to be improved using mount_unionfs
# because the default implementation in rc.subr does not allow
# to use the copymode=transparent. This is needed because /var
# is created before this script is executed, so it already contains
# data and sub directories that should be accessed transparently
# (mdmfs does not provide the feature to access sub-dirs, e.g. new
# created data in /var/run will not be stored in the memory files
# system, only data created in /var).
#   $1 = size
#   $2 = mount point
#   $3 = (optional) extra flags
mount_md()
{
	if [ -n "$3" ]; then
		flags="$3"
	fi
	device=$(/sbin/mdconfig -a -t swap -s ${1})
	/sbin/newfs /dev/${device} > /dev/null 2>&1
	/bin/mkdir -p ${varmfs_root}/${device}
	/sbin/mount /dev/${device} ${varmfs_root}/${device}
	/sbin/mount_unionfs ${flags} ${varmfs_root}/${device} ${2}
}

# If we do not have a writable /var, create a memory filesystem for /var
# unless told otherwise by rc.conf.  We don't have /usr yet so use mkdir
# instead of touch to test.  We want mount to record its mounts so we
# have to make sure /var/db exists before doing the mount -a.
#
case "${varmfs}" in
[Yy][Ee][Ss])
	mount_md ${varsize} /var "${varmfs_flags}"
	;;
[Nn][Oo])
	;;
*)
	if /bin/mkdir -p /var/.diskless 2> /dev/null; then
		rmdir /var/.diskless
	else
		mount_md ${varsize} /var "${varmfs_flags}"
	fi
esac

# Make sure we have /var/log/lastlog and /var/log/wtmp files
if [ ! -f /var/log/lastlog ]; then
	cp /dev/null /var/log/lastlog
	chmod 644 /var/log/lastlog
fi
if [ ! -f /var/log/wtmp ]; then
	cp /dev/null /var/log/wtmp
	chmod 644 /var/log/wtmp
fi
