#!/bin/sh
# Copyright (c) 2008 Volker Theile (votdev@gmx.de)
# All rights reserved.

# PROVIDE: websrv_htpasswd
# REQUIRE: userdb DAEMON
# XQUERY: -i "count(//websrv/enable) > 0 and count(//websrv/authentication) > 0" -o "0" -b
# RCVAR: websrv_htpasswd

. /etc/rc.subr
. /etc/configxml.subr

if configxml_isset //websrv/authentication; then
	# Defaults
	documentroot=`configxml_get "//websrv/documentroot"`
	htpasswdfile=".websrv_htpasswd"
	htpasswd="${documentroot}/${htpasswdfile}"
	
	echo "Generating ${htpasswdfile}."
	
	# Generate the htpasswd file used by websrv.
	# Add aministrator account.
	/usr/local/bin/xml sel -t \
		-v "concat(//system/username,':',//system/password)" \
		${configxml_file} | /usr/local/bin/xml unesc > ${htpasswd}
	
	# Add configured users. Parse /etc/master.passwd to get password.
	# Did not find a better solution. Using PHP crypt fails when calling via WebGUI.
	/usr/local/bin/xml sel -t -m "//access/user" \
		-v login \
		-i "position() != last()" -n -b \
		${configxml_file} | /usr/local/bin/xml unesc | \
		while read _login; do
			_password=`/bin/cat /etc/master.passwd | /usr/bin/grep "^${_login}:*" | /usr/bin/awk '{split($0,a,":"); print a[2]}'`
			echo "${_login}:${_password}" >> ${htpasswd}
		done
	
	/bin/chmod 0600 ${htpasswd}
fi
