#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/wpa_supplicant,v 1.1.2.1.8.1 2008/10/02 02:57:24 kensmith Exp $
#
# Modified by Volker Theile (votdev@gmx.de)
#

# PROVIDE: wpa_supplicant
# REQUIRE: mountcritremote
# KEYWORD: nojail nostart
# XQUERY: -i "count(//interfaces/*/wpa/enable) > 0" -o "0" -b
# RCVAR: wpa_supplicant

. /etc/rc.subr
. /etc/network.subr
. /etc/configxml.subr

name="wpa_supplicant"
rcvar=
command="/usr/sbin/${name}"
conf_file="/var/etc/wpa_supplicant.conf"

ifn="$2"
if [ -z "$ifn" ]; then
	return 1
fi

case ${ifn} in
ndis*)
	driver="ndis"
	;;
*)
	driver="bsd"
	;;
esac

# Create wpa_supplicant.conf
/usr/local/bin/xml sel -t -m "//interfaces/*/wireless/wpa[enable]" \
	-o "network={" -n \
	-v "concat('ssid=&quot;',../ssid,'&quot;')" -n \
	-v "concat('key_mgmt=',keymgmt)" -n \
	-v "concat('pairwise=',pairwise)" -n \
	-v "concat('group=',pairwise)" -n \
	-v "concat('psk=&quot;',psk,'&quot;')" -n \
	-o "}" -n \
	${configxml_file} | /usr/local/bin/xml unesc > ${conf_file}

load_rc_config $name

pid_file="/var/run/${name}/${ifn}.pid"
command_args="-B -q -i $ifn -c $conf_file -D $driver -P $pid_file"
required_files=$conf_file

run_rc_command "$1"
