#!/usr/local/bin/php -f
<?php
/*
	inadyn init script to create config file

	Copyright © 2007 Volker Theile (votdev@gmx.de)
  All rights reserved.

	part of FreeNAS (http://www.freenas.org)
	Copyright (C) 2005-2007 Olivier Cochard-Labbe <olivier@freenas.org>.
	All rights reserved.

	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are met:

	1. Redistributions of source code must retain the above copyright notice,
	   this list of conditions and the following disclaimer.

	2. Redistributions in binary form must reproduce the above copyright
	   notice, this list of conditions and the following disclaimer in the
	   documentation and/or other materials provided with the distribution.

	THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
	INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
	AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
	AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
	OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
	SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
	INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
	CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
	ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
	POSSIBILITY OF SUCH DAMAGE.
*/
	require_once("config.inc");
	require_once("functions.inc");
	require_once("util.inc");

	global $config, $g;

	$fd = fopen("{$g['varetc_path']}/inadyn.conf", "w");
	if (!$fd) {
		$message = "Error: Failed to create '{$g['varetc_path']}/inadyn.conf'";
		write_console($message . ".\n");
		write_log($message);
		return 1;
	}

	/* Get the service type */
	$servicetype = "";
	switch($config['dynamicdns']['provider']) {
		case "dyndns.org":					$servicetype = "dyndns@dyndns.org";
																break;
		case "freedns.afraid.org":	$servicetype = "default@freedns.afraid.org";
																break;
		case "zoneedit.com":				$servicetype = "default@zoneedit.com";
																break;
		case "no-ip.com":						$servicetype = "default@no-ip.com";
																break;
	}

	/* Set command parameters. */
	$inadynconf = <<<EOD
--background
--syslog
--dyndns_system {$servicetype}
--alias {$config['dynamicdns']['domainname']}
--username "{$config['dynamicdns']['username']}"
--password "{$config['dynamicdns']['password']}"

EOD;

	/* Set additional command parameters. */
	if ($config['dynamicdns']['updateperiod']) {
		$inadynconf .= <<<EOD
--update_period_sec {$config['dynamicdns']['updateperiod']}

EOD;
	}

	if ($config['dynamicdns']['forcedupdateperiod']) {
		$inadynconf .= <<<EOD
--forced_update_period {$config['dynamicdns']['forcedupdateperiod']}

EOD;
	}

	fwrite($fd, $inadynconf);
	fclose($fd);

	return 0;
?>
