						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>
<div id="footer">
	<table border="0" cellspacing="0" cellpadding="0" height="100%" width="100%">
		<tr>
			<td align="center" valign="middle">
				<span class="pgfootertext"><?=get_product_name();?> <?=str_replace("Copyright (C)","&copy;",get_product_copyright());?> <a href="http://www.tibet.com/" class="tblnk">&nbsp;</a>[<a href="/license.php" class="tblnk"><?=gettext("View license");?></a>]</span>
			</td>
		</tr>
	</table>
</div>
</body>
</html>
