install:
	@${INSTALL_PROGRAM} /usr/sbin/nfsd $(FREENAS)/usr/sbin
	@${INSTALL_PROGRAM} /usr/sbin/mountd $(FREENAS)/usr/sbin
	@${INSTALL_PROGRAM} /usr/sbin/rpcbind $(FREENAS)/usr/sbin

.include "bsd.freenas.mk"
